steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  env: ['CI=true']
  args: ['run', 'build']
artifacts:
  objects:
    location: 'gs://static.gieffektivt.no/'
    paths: ['dist/**/**']